#ifndef QTJAMBI_METAINFO_H
#define QTJAMBI_METAINFO_H

#include "qtjambi_core.h"
#if defined(JNI_VERSION_1_8)
#define QTJAMBI_ONLOAD_RETURN JNI_VERSION_1_8
#elif defined(JNI_VERSION_1_6)
#define QTJAMBI_ONLOAD_RETURN JNI_VERSION_1_6
#else
#define QTJAMBI_ONLOAD_RETURN JNI_VERSION_1_5
#endif

#endif // QTJAMBI_METAINFO_H
