/****************************************************************************
**
** Copyright (C) 2009-2015 Peter Droste, Omix Visualization GmbH & Co. KG. All rights reserved.
**
** This file is part of Qt Jambi.
**
** ** $BEGIN_LICENSE$
**
** GNU Lesser General Public License Usage
** This file may be used under the terms of the GNU Lesser
** General Public License version 2.1 as published by the Free Software
** Foundation and appearing in the file LICENSE.LGPL included in the
** packaging of this file.  Please review the following information to
** ensure the GNU Lesser General Public License version 2.1 requirements
** will be met: http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html.
**
** In addition, as a special exception, Nokia gives you certain
** additional rights. These rights are described in the Nokia Qt LGPL
** Exception version 1.0, included in the file LGPL_EXCEPTION.txt in this
** package.
**
** GNU General Public License Usage
** Alternatively, this file may be used under the terms of the GNU
** General Public License version 3.0 as published by the Free Software
** Foundation and appearing in the file LICENSE.GPL included in the
** packaging of this file.  Please review the following information to
** ensure the GNU General Public License version 3.0 requirements will be
** met: http://www.gnu.org/copyleft/gpl.html.
**
** $END_LICENSE$
**
** This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
** WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
**
****************************************************************************/


#ifndef _Included_org_qtjambi_qt_declarative_QDeclarativeList
#define _Included_org_qtjambi_qt_declarative_QDeclarativeList

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <QtCore/qglobal.h>
#ifdef Q_OS_MAC
#  include <JavaVM/jni.h>
#else
#  include <jni.h>
#endif
#include <QtDeclarative>

/* Header for class org_qtjambi_qt_declarative_QDeclarativeListReference */

class Q_DECL_EXPORT QtjambiDeclarativeListProperty : public QDeclarativeListProperty<QObject>{
public:
    typedef void* (*CopyFunction)(void *);
    typedef void (*DeleteFunction)(void *);

    QtjambiDeclarativeListProperty();
    QtjambiDeclarativeListProperty(const QtjambiDeclarativeListProperty&);
    QtjambiDeclarativeListProperty(QObject *o, QList<QObject*> &list);
    ~QtjambiDeclarativeListProperty();

    virtual QObject *object();

    virtual void append(QObject* object);

    virtual int count();

    virtual QObject* at(int index);

    virtual void clear();

    virtual bool canAppend();

    virtual bool canAt();

    virtual bool canClear();

    virtual bool canCount();

private:
    QtjambiDeclarativeListProperty(QObject *o, void* d, CopyFunction g, DeleteFunction f, AppendFunction a, CountFunction c, AtFunction t, ClearFunction r );

    template<class T>
    static void appendListProperty(QDeclarativeListProperty<QObject> * propertyList, QObject* newEntry){
        QDeclarativeListProperty<T >* list = static_cast<QDeclarativeListProperty<T >*>(propertyList->data);
        list->append(list, static_cast<T *>(newEntry));
    }

    template<class T>
    static int countListProperty(QDeclarativeListProperty<QObject> * propertyList){
        QDeclarativeListProperty<T >* list = static_cast<QDeclarativeListProperty<T >*>(propertyList->data);
        return list->count(list);
    }

    template<class T>
    static QObject* atListProperty(QDeclarativeListProperty<QObject> * propertyList, int index){
        QDeclarativeListProperty<T >* list = static_cast<QDeclarativeListProperty<T >*>(propertyList->data);
        return static_cast<QObject*>(list->at(list, index));
    }

    template<class T>
    static void clearListProperty(QDeclarativeListProperty<QObject> * propertyList){
        QDeclarativeListProperty<T >* list = static_cast<QDeclarativeListProperty<T >*>(propertyList->data);
        list->clear(list);
    }

    template<class T>
    static void deleteListProperty(void* data){
        QDeclarativeListProperty<T >* list = static_cast<QDeclarativeListProperty<T >*>(data);
        delete list;
    }

    template<class T>
    static void* copyListProperty(void* data){
        if(data){
            QDeclarativeListProperty<T >* list = static_cast<QDeclarativeListProperty<T >*>(data);
            return new QDeclarativeListProperty<T >(list->object,
                                            list->data,
                                            list->append,
                                            list->count,
                                            list->at,
                                            list->clear);
        }else{
            return Q_NULLPTR;
        }
    }

public:
    template<class T>
    static QtjambiDeclarativeListProperty* createFrom(const QDeclarativeListProperty<T>& d)
    {
        QtjambiDeclarativeListProperty::AppendFunction appendFunction = Q_NULLPTR;
        QtjambiDeclarativeListProperty::CountFunction countFunction = Q_NULLPTR;
        QtjambiDeclarativeListProperty::AtFunction atFunction = Q_NULLPTR;
        QtjambiDeclarativeListProperty::ClearFunction clearFunction = Q_NULLPTR;
        if(d.append){
            appendFunction = &QtjambiDeclarativeListProperty::appendListProperty<T>;
        }
        if(d.count){
            countFunction = &QtjambiDeclarativeListProperty::countListProperty<T>;
        }
        if(d.at){
            atFunction = &QtjambiDeclarativeListProperty::atListProperty<T>;
        }
        if(d.clear){
            clearFunction = &QtjambiDeclarativeListProperty::clearListProperty<T>;
        }
        return new QtjambiDeclarativeListProperty(
                    d.object,
                    const_cast<void*>(static_cast<const void*>(&d)),
                    &copyListProperty<T>,
                    &deleteListProperty<T>,
                    appendFunction,
                    countFunction,
                    atFunction,
                    clearFunction
                );
    }
private:
    CopyFunction m_copyFunction;
    DeleteFunction m_deleteFunction;
};


#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_qtjambi_qt_declarative_QDeclarativeListReference
 * Method:    listElementType
 * Signature: (J)Ljava/lang/Class;
 */
JNIEXPORT jclass JNICALL Java_org_qtjambi_qt_declarative_QDeclarativeListReference__1_1qt_1listElementType
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
